### ISSUE TITLE
Router.go?

### ISSUE THREAD

**Issue by gamedolphin** [jamielob/transitions#10]
Is there a way to control transitions from the router.go method? It would be helpful if there was, removing the dependence on the view and also transitions to non-linked containers at will be possible.

**Comment by jamielob** [comment]
Hi @gamedolphin.  Can you show me a code example of what you mean?  If you set the default transitions and then call router.go it should work.

**Comment by gamedolphin** [comment]
Aren't default transitions a global default? If they are set to slideInLeft and slideInRight, how to get a page to slideInTop from Router.go?

**Comment by gamedolphin** [comment]
Also, can I force the same route to transition to itself? For example, a route controlled through a path like "/custom-path-:_id" where id is changing does not transition even when transitions are applied in the hrefs.

**Comment by jamielob** [comment]
The package uses Meteor's _uihooks to create the transitions.  Basically, any time that a template containing the .transitions-content div is swapped out for a different template containing a .transitions-content div it animates it.  This meant that the method of causing that template change shouldn't matter (Router.go or a link are essentially causing the same thing to happen).   For that same reason, animating a "transition to self" isn't going to work, because the template isn't being swapped out.   You could do that with dynamic content and inline transitions though.
